### ISSUE TITLE
生成的抓取位姿是不是相对于相机坐标系的

### ISSUE THREAD

**Issue by quanfeifan** [luyh20/FGC-GraspNet#10]
对于生成的抓取位姿不是很理解

**Comment by luyh20** [comment]
模型预测的旋转参数是从抓取姿势到可视化坐标系夹爪的原轴的旋转矩阵。可视化坐标系可能与相机坐标系不匹配，而且夹爪TCP坐标系和相机坐标系可能也有一个旋转矩阵。在真机实验中你需要确定这些坐标系的关系。你可以使用一个单位矩阵作为grasp pose的旋转矩阵可视化一下，或许你会更清楚这些坐标系的关系。
