### ISSUE TITLE
关于test.py的问题

### ISSUE THREAD

**Issue by songhat** [luyh20/FGC-GraspNet#4]
我运行test.py时，ind_find函数报错
```bash
Traceback (most recent call last):
  File "/mnt/d/all_codes/Grasp/graspnet-baseline/test2.py", line 176, in <module>
    evaluate()
  File "/mnt/d/all_codes/Grasp/graspnet-baseline/test2.py", line 111, in evaluate
    ind1_ = ind_find(preds, gg1_)
  File "/mnt/d/all_codes/Grasp/graspnet-baseline/test2.py", line 73, in ind_find
    idx = np.where((a == b[:, None]).all(-1))[1]
AttributeError: 'bool' object has no attribute 'all'
INFO - 2023-07-24 19:03:34,870 - core - signal_shutdown [atexit]

```

**Comment by luyh20** [comment]
这个BUG看起来应该是(a == b[:, None])维度不一致导致的

**Comment by 1mingW** [comment]
I've also met this error. The code did NMS to `gg`, but nothing to `preds`, so `preds` and `gg1_` don't have the same dimension.  How did you solve it?

**Comment by songhat** [comment]
> I've also met this error. The code did NMS to `gg`, but nothing to `preds`, so `preds` and `gg1_` don't have the same dimension. How did you solve it?
just use the source code. don't change any code. It works.

**Comment by songhat** [comment]
> I've also met this error. The code did NMS to `gg`, but nothing to `preds`, so `preds` and `gg1_` don't have the same dimension. How did you solve it?

just use the source code. don't change any code. it works
